# Python, the Basics
Author: Kaihang Zhang<br>
Email: [khzhang2@connect.hku.hk](mailto:khzhang2@connect.hku.hk)<br>
231 Haking Wong Building seat 64, The University of Hong Kong<br>

Created: December 10th, 2022<br>
Last revised: December 5th, 2023
### Table of Contents
- [Data Types](#Data_Types)
  - [Data](#Data)
  - [Data Structures](#Data_Structures)
- [Writing a Loop](#Writing_a_Loop)
- [Writing an if sentence](#Writing_an_if_sentence)
- [Operations: Methods, Functions](#Operations_Methods_Functions)
  - [Define function](#Define_function)

## Data_Types

### Data

In [1]:
# int
var = 1
print(var)
print(type(var))

1
<class 'int'>


In [2]:
# float
var = 1.
print(var)
print(type(var))

1.0
<class 'float'>


In [3]:
# string
var = '1'
print(var)
print(type(var))

1
<class 'str'>


In [4]:
# boolean
var = bool(1)
print(var)
print(type(var))

True
<class 'bool'>


### Data_Structures

In [5]:
# list
data_struct = [1, 2., '3']
print(data_struct)
print(type(data_struct))
print('\n')

# add an element to list
data_struct.append(10)
print('The list after adding an element is:')
print(data_struct)
print('\n')

# extend list
print('The list after extending itself is:')
data_struct.extend(data_struct)
print(data_struct)

[1, 2.0, '3']
<class 'list'>


The list after adding an element is:
[1, 2.0, '3', 10]


The list after extending itself is:
[1, 2.0, '3', 10, 1, 2.0, '3', 10]


In [6]:
# dict
data_struct = {'integer':1, 'string':'2', 'float_num':3.}
print('The dict is:')
print(data_struct)
print('\n')
print('The data type is:')
print(type(data_struct))
print('\n')

# add item to dict
print('The dict after adding a list is:')
data_struct['list'] = [1, 2, 3]
print(data_struct)

The dict is:
{'integer': 1, 'string': '2', 'float_num': 3.0}


The data type is:
<class 'dict'>


The dict after adding a list is:
{'integer': 1, 'string': '2', 'float_num': 3.0, 'list': [1, 2, 3]}


In [7]:
# array
import numpy as np
data_struct = np.array([[1, 2, 3], [4, 5, 6]])
print('The array is:')
print(data_struct)
print('\n')
print('The data type is:')
print(type(data_struct))
print('\n')

# access the shape of array
print('The shape of the array')
print(data_struct.shape)
print('\n')

# matrix transpose
print('The transposed array is:')
print(data_struct.T)
print('\n')

# matrix multiplication
print('Matrix multiplication example result:')
print(data_struct @ data_struct.T)
print('\n')

#element-wise product of arrays
print('Matrix multiplication example result:')
print(data_struct * data_struct)
print('\n')


The array is:
[[1 2 3]
 [4 5 6]]


The data type is:
<class 'numpy.ndarray'>


The shape of the array
(2, 3)


The transposed array is:
[[1 4]
 [2 5]
 [3 6]]


Matrix multiplication example result:
[[14 32]
 [32 77]]


Matrix multiplication example result:
[[ 1  4  9]
 [16 25 36]]




In [8]:
# DataFrame
import pandas as pd
array = np.array([[1, 2, 3], [4, 5, 6]])
print('The DataFrame is:')
data_struct = pd.DataFrame(array, index=['row1', 'row2'], columns=['column1', 'column2', 'column3'])
print(data_struct)
print('\n')

# detailed pandas quick tutorials can be found at
# https://pandas.pydata.org/docs/user_guide/10min.html#min

The DataFrame is:
      column1  column2  column3
row1        1        2        3
row2        4        5        6




In [9]:
# tensor
import torch
print('The tensor is:')
array = np.array([[1, 2, 3], [4, 5, 6]])
data_struct = torch.tensor(array)
print(data_struct)
print('\n')

# detailed pytorch quick tutorials can be found at
# https://pytorch.org/tutorials/

The tensor is:
tensor([[1, 2, 3],
        [4, 5, 6]])




## Writing_a_Loop

### "for" loop

In [10]:
max_num_iter = 5  # the maximum number of iteration

# "i" is a temporary variable to use in each iteration
# "range" is a build-in function to generate iterable values
for i in range(max_num_iter):
    print(i)
# Note: the index number in Python starts from 0, not 1!


0
1
2
3
4


In [11]:
for i in range(2, 7):
    print(i)
# Note that the starting point of range(x, y)
# is included but the ending point is not
# (x is included but y is excluded)

2
3
4
5
6


In [12]:
# "for" loop and list
test_list = []  # create an empty list
print('list before adding value is', test_list)
for i in range(5):
    test_list.append(i)

print('list after adding value is', test_list)

list before adding value is []
list after adding value is [0, 1, 2, 3, 4]


### "while" loop

In [13]:
# in "while" loop, an iterable variable must be pre-specified
c = 0
while c<5:
    print(c)
    c = c + 1

# Personally, "for" loop is more used than "while" loop

0
1
2
3
4


## Writing_an_if_sentence

### We want to do the following:

Given a list consists of several numbers, if the sum of the numbers is greater than 0, print "positive list", if the sum of the numbers is less than 0, print "negative list", otherwise, print "zero sum".

In [5]:
# given a random list
# you can modify by yourself!
lst = [2, -3, -4, 8]


In [6]:
if sum(lst) > 0:
    print("positive list")
elif sum(lst) < 0:
    print("negative list")
else:
    print("zero sum")

positive list


## Operations_Methods_Functions

In [14]:
print('append is a method')
test_list = []
test_list.append(1)
print(test_list)

append is a method
[1]


In [15]:
print('There is no output for a method:')
test_list = []
print(test_list.append(1))

There is no output for a method:
None


In [16]:
print('sum is a function')
test_list = [1, 2, 3]
summation = sum(test_list)
print(summation)

sum is a function
6


In [17]:
# now we try to sort the DataFrame by the first column
# by descending order
print('pd.sort_values is a function')
test_df = pd.DataFrame(array, index=['row1', 'row2'], columns=['column1', 'column2', 'column3'])

print(test_df.sort_values(by='column1', ascending=False))
print('\n')

# apply sort_values
test_df.sort_values(by='column1', ascending=False)
print('If no value assignment, the original DataFrame remains unchanged', '\n', test_df)
print('\n')

# The correct approach is to assign the sorted DataFrame to itself
print('The DataFrame is now sorted!')
test_df = test_df.sort_values(by='column1', ascending=False)
print(test_df)


pd.sort_values is a function
      column1  column2  column3
row2        4        5        6
row1        1        2        3


If no value assignment, the original DataFrame remains unchanged 
       column1  column2  column3
row1        1        2        3
row2        4        5        6


The DataFrame is now sorted!
      column1  column2  column3
row2        4        5        6
row1        1        2        3


### Define_function

In [18]:
def my_function(input1, input2):
    # write your funciton details here
    # consider both inputs are numerical values (int, float)
    output = input1 + input2
    return output

In [19]:
my_function(1, 2)

3